project:
  type: website
  output-dir: docs

cache: true

website:
  title: "Wheat head Blast Epidemic Analog Conditions"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
        icon: house
      - href: CORDEX_Retrieval.qmd
        text: Weather Data
        icon: cloud-download
      - href: AnalogYearsProc.qmd
        text: Data Analysis
        icon: bar-chart
  page-footer:
    center: |
      ::: {.html}
      Igor Erhardt · Universidade Federal de Viçosa (UFV)
      <a href="https://www.linkedin.com/in/igor-fernandes-erhardt-572180232" target="_blank" title="LinkedIn">
        <i class="bi bi-linkedin"></i>
      </a>
      <br>
  
      Adam Sparks · Curtin University
      <a href="https://adamhsparks.netlify.app/" target="_blank" title="Website">
        <i class="bi bi-globe"></i>
      </a>
      <br>
  
      Emerson Del Ponte · Universidade Federal de Viçosa (UFV)
      <a href="https://emersondelponte.netlify.app/" target="_blank" title="Website">
        <i class="bi bi-globe"></i>
      </a>
      :::
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  warning: false
  message: false

editor: visual

